name: Simple JUnit Tests

on:
  push:
    branches:
      - '*'


jobs:
  test:
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest', 'macos-latest' ]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'maven'

      - name: Run Maven Action
        run: mvn -B test --file pom.xml
